### ISSUE TITLE
grid syntax is weird

### ISSUE THREAD

**Issue by vvval** [spiral/toolkit#153]
lets pretend we have next grid row columns:
```json
{
  "name": "name",
  "fullName": "full name",
}
```
And I want to use a sorting here:
right now, sort name and column name are tied together:
```html
<grid:cell.text name="fullName" label="[[Name]]" sort="true" body="{fullName}" sort-dir="asc" sort-default="true"/>
```
> body? what for?

What I propose is to explicitly and separately define column and sorter name:
```html
<grid:cell.text name="fullName" label="[[Name]]" sort="name" sort-dir="asc" sort-default="true"/>
```
> Meaning render `fullName` column and apply a sorter named `name`

**Comment by AndrewKirkovski** [comment]
Right now you are expected to name column based on sort you wanna use, than customize render if needed
i.e.
`<grid:cell.text name="name" label="[[Name]]" sort="true" body="{firstName} {lastName}"/>`

Creates a column that is named as "name", uses sort "name", but is rendered as custom data
So semantics goes first, representation is customizable
